name: Docker CI

on:
  push:
    branches:
      - main  # Cambia con il tuo branch principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn package --settings .github/mvn-settings.xml

      - name: Build Docker image
        run: docker build . -t your-docker-image-name:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sinoboo
          password: Comeiocomanda99.

      - name: Push Docker image
        run: docker push your-docker-image-name:latest
